# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SPH4Nc5l5FS11yYW7s+UOc2e2K/O9/tqDae0L644uVt86MR6FKt6m++e5POUvdO06g+Sy3z5v25VnX5ezieN6I9Fcbm/b9V/6aXxQ+wwuV+acYH96CeFUKhPhgbLhGXK4CEZltM4Ej1GIxRHceGQNJT1w7/+OQw98j3nnR3l0FY2gmXC4OsXITXfdO5IR86+r6Wy4t6ef65Ayb90+uRVhDXRd2bkahL6KJ1rFiw2hz9MnRbuPRrPy+kHC/ZbBxPIcjjiTgjikdsyBWNQVfCySJugOOnvZ1yJMxHJb+Vbbitsd3jPBfQpsdf+Uajbz+75ApQdm0MevoFvEiBqzq4L6xfnhAkA9kQW2bLG7e/7753lw8Wl7X8Fi4U5p7F9ddl1ef3EhPXAibE6lkpj7DsOZPlH+86ZX/5D1rRtCO2J5sMBMWyeTB6cql96m6bBUf6ouPXrfPGpLGcPM1QXXGsjxuUTiIX1E1MfFMwamfkhC8hd9qaPv5trjlDLWS0DQXpDuxWON+umlnA3IASEj2KXJ6FEVwUs1lNSbVa4VbFZgZAlf6CUfkqKFowDJDL9SH/7EWKp0ee6GRb77JKGQ9T2us+ja2riFulmhYvhT1WiMJJFECIlHAwZ6roO1fTrWvhSJ0WdnuMNiQcsxiRHo+jWfhtEHimJ/c+oBr5xVarCWk4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
