appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SPH4Nc5l5FS11yYW7s+UOc2e2K/O9/tqDae0L644uVt86MR6FKt6m++e5POUvdO06g+Sy3z5v25VnX5ezieN6I9Fcbm/b9V/6aXxQ+wwuV+acYH96CeFUKhPhgbLhGXK4CEZltM4Ej1GIxRHceGQNJT1w7/+OQw98j3nnR3l0FY2gmXC4OsXITXfdO5IR86+r6Wy4t6ef65Ayb90+uRVhDXRd2bkahL6KJ1rFiw2hz9MnRbuPRrPy+kHC/ZbBxPIcjjiTgjikdsyBWNQVfCySJugOOnvZ1yJMxHJb+Vbbitsd3jPBfQpsdf+Uajbz+75ApQdm0MevoFvEiBqzq4L6xfnhAkA9kQW2bLG7e/7753lw8Wl7X8Fi4U5p7F9ddl1ef3EhPXAibE6lkpj7DsOZPlH+86ZX/5D1rRtCO2J5sMBMWyeTB6cql96m6bBUf6ouPXrfPGpLGcPM1QXXGsjxuUTiIX1E1MfFMwamfkhC8hd9qaPv5trjlDLWS0DQXpDuxWON+umlnA3IASEj2KXJ6FEVwUs1lNSbVa4VbFZgZAlf6CUfkqKFowDJDL9SH/7EWKp0ee6GRb77JKGQ9T2us+ja2riFulmhYvhT1WiMJJFECIlHAwZ6roO1fTrWvhSJ0WdnuMNiQcsxiRHo+jWfhtEHimJ/c+oBr5xVarCWk4=
conda_forge_output_validation: true
